//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalDenuncia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCOMISARIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBCOMISARIA()
        {
            this.TBDELEGADOS = new HashSet<TBDELEGADO>();
            this.TBDENUNCIAS = new HashSet<TBDENUNCIA>();
            this.TBPOLICIAS = new HashSet<TBPOLICIA>();
        }
    
        public int idcomisaria { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public int iddistrito { get; set; }
    
        public virtual TBDISTRITO TBDISTRITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBDELEGADO> TBDELEGADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBDENUNCIA> TBDENUNCIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBPOLICIA> TBPOLICIAS { get; set; }
    }
}
