//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalDenuncia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBDENUNCIA
    {
        public int iddenuncia { get; set; }
        public string descripcion { get; set; }
        public string direccion { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> idusuario { get; set; }
        public int idtipo { get; set; }
        public int iddistrito { get; set; }
        public Nullable<int> idpolicia { get; set; }
        public Nullable<int> idcomisaria { get; set; }
        public int idestado { get; set; }
        public Nullable<int> idverazidad { get; set; }
        public Nullable<int> iddelegado { get; set; }
    
        public virtual TBCOMISARIA TBCOMISARIA { get; set; }
        public virtual TBDELEGADO TBDELEGADO { get; set; }
        public virtual TBDISTRITO TBDISTRITO { get; set; }
        public virtual TBESTADO TBESTADO { get; set; }
        public virtual TBPOLICIA TBPOLICIA { get; set; }
        public virtual TBTIPODENUNCIA TBTIPODENUNCIA { get; set; }
        public virtual TBUSUARIO TBUSUARIO { get; set; }
        public virtual TBVERAZIDAD TBVERAZIDAD { get; set; }
    }
}
