//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalDenuncia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBPOLICIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBPOLICIA()
        {
            this.TBDENUNCIAS = new HashSet<TBDENUNCIA>();
        }
    
        public int idpolicia { get; set; }
        public string dni { get; set; }
        public string nombre { get; set; }
        public string apellidopa { get; set; }
        public string apellidoma { get; set; }
        public string cargo { get; set; }
        public int idcomisaria { get; set; }
    
        public virtual TBCOMISARIA TBCOMISARIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBDENUNCIA> TBDENUNCIAS { get; set; }
    }
}
